version: 2.1

orbs:
  docker: circleci/docker@2.1.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build:
          image: node-js-server
          tag: latest
      - docker/push:
          image: deflaxx/node-js-server
          tag: latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

