version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  build-and-publish-docker-image:
    jobs:
      docker-password: DOCKER_PASSWORD
      docker-username: DOCKER_USERNAME
      image: deflaxx/node-js-sample
      tag: 0.1.$CIRCLE_BUILD_NUM
